import type { Metadata } from 'next';
import { profile } from '@/data/profile';
import { projects } from '@/data/projects';
import { capabilities } from '@/data/capabilities';
import { TextLink } from '@/components/ui/Primitives';
import { SafeImage } from '@/components/ui/SafeImage';
import { Footer } from '@/components/layout/Footer';
import { canonical } from '@/lib/seo';
export const metadata: Metadata = { title: 'Quick view — Muhammad Syahmi', description: 'A concise overview of Muhammad Syahmi: cloud computing student, projects, core capabilities and contact.', alternates: { canonical: canonical('/quick') } };
export default function QuickPage() {
  return <><main id="main" className="section quick-page"><div className="quick-page-top mono"><span>THE 30-SECOND VERSION</span><TextLink href="/">Full experience</TextLink></div><header className="quick-hero"><div><h1>Muhammad<br />Syahmi<span>.</span></h1><p className="quick-role">Cloud Computing Student · Malaysia</p><p>{profile.description}</p><div className="quick-contact"><TextLink href={`mailto:${profile.email}`}>Email me</TextLink><TextLink href={profile.github} external>GitHub</TextLink><TextLink href={profile.resumeUrl}>Request resume</TextLink></div></div><SafeImage src="/images/syahmi.webp" alt="Muhammad Syahmi outdoors in Malaysia" width={960} height={1280} sizes="(max-width: 760px) 30vw, 220px" priority /></header><section className="quick-section"><h2>Selected work</h2><div className="quick-projects">{projects.map(project => { const isInternalCaseStudy = project.featured || project.liveUrl?.startsWith('/'); return <article key={project.slug}><div><h3>{project.title}</h3><span className="mono muted">{project.featured ? 'FLAGSHIP / ' : ''}PUBLIC PROJECT</span></div><p>{project.description}</p><p className="quick-stack mono">{project.stack.join(' / ')}</p><TextLink href={project.featured ? '/projects/greetly' : (project.liveUrl?.startsWith('/') ? project.liveUrl : project.github!)} external={!isInternalCaseStudy}>{isInternalCaseStudy ? 'Read case study' : 'View source'}</TextLink></article> })}</div></section><section className="quick-section"><h2>Capabilities, with context</h2><div className="quick-capabilities">{capabilities.map(capability => <div key={capability.name}><h3>{capability.name}</h3><span className="mono signal-text">{capability.level.replaceAll('-', ' ')}</span><p>{capability.technologies.join(' · ')}</p></div>)}</div></section><section className="quick-section quick-notes"><div><h2>Learning & credentials</h2><p>Certifications are self-reported on my public profile; issuer verification links are not yet provided. Future professional and cloud certifications are shown separately as targets.</p><TextLink href="/#credentials">View learning passport</TextLink></div><div><h2>Where I’m heading</h2><p>From cloud computing studies toward cloud and DevOps engineering, then platform engineering and AI infrastructure.</p><p>For a CV or a conversation about a project, email <a href={`mailto:${profile.email}`}>{profile.email}</a>.</p></div></section></main><Footer compact /></>;
}
