import { SectionLabel, TextLink } from '@/components/ui/Primitives';
import { SafeImage } from '@/components/ui/SafeImage';
export function About() {
  return <section id="about" className="section about-section" aria-labelledby="about-title"><SectionLabel number="01">Behind the system</SectionLabel><div className="about-grid"><div className="about-copy"><h2 id="about-title">Curious by nature.<br /><span className="muted">Builder by choice.</span></h2><p className="large-body">I’m Muhammad Syahmi.<br />A cloud computing student who likes knowing how the whole thing works.</p><p>Interfaces are where I start. What keeps me interested is everything behind them: the network, the data, the deployment, and the small decisions that make a system hold together.</p><p>Right now, I’m connecting software with cloud infrastructure and edge devices, while exploring how AI agents can become useful parts of those systems.</p><TextLink href="/quick">The 30-second version</TextLink><dl className="about-facts"><div><dt>NOW</dt><dd>Cloud Computing Student</dd></div><div><dt>NEXT</dt><dd>Cloud / DevOps Engineer</dd></div><div><dt>EXPLORING</dt><dd>AI infrastructure & agentic systems</dd></div></dl></div><figure className="portrait"><SafeImage src="/images/syahmi.webp" alt="Muhammad Syahmi beside a river and forested limestone hills in Malaysia" width={960} height={1280} sizes="(max-width: 760px) 90vw, 40vw" /><figcaption><span>MUHAMMAD SYAHMI</span><span>MALAYSIA / MY</span></figcaption><span className="portrait-cross" aria-hidden="true">+</span></figure></div></section>;
}

export function Philosophy() {
  return <section className="philosophy section" aria-label="Engineering philosophy"><div className="philosophy-line" aria-hidden="true"><span /><i /><span /></div><p>I don’t just build interfaces.<br /><span>I think about what<br />runs behind them.</span></p><div className="philosophy-topics mono"><span>Infrastructure</span><span>Automation</span><span>Data</span><span>Intelligence</span></div><p className="philosophy-note">Systems should feel invisible when they work well.</p></section>;
}
